version: "3"

# INSTALL NEW NPM MODULE:
# docker exec -it shutdown_frontend bash
# npm i module

services:
  frontend:
    container_name: shutdown_frontend
    build: frontend
    restart: always
    command: npm run serve
    environment:
      API_URL: http://backend:4000/api
      CHOKIDAR_USEPOLLING: 'true'
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/data
      - /data/node_modules
    tty: true
    

  backend:
    container_name: shutdown_backend
    build: ./backend
    environment:
      SECRET: '1r3jTQUSuKOQEUuT2eiusYpKLLde4kdA'
    ports:
      - 4000:4000
    volumes:
      - ./backend:/data
      - /data/node_modules